{{- if .Values.vaultSecrets.enabled }}
{{- $tenant := .Values.vaultSecrets.tenant }}
{{- range .Values.vaultSecrets.secrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  namespace: {{ .namespace | default "default" }}
spec:
  secretStoreRef:
    name: mosler-{{ $tenant }}
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: {{ .source }}
{{- end }}
{{- end -}}
