{{- if .Values.prometheusServiceMonitor.enabled }}
{{- $appName := include "web-service.name" . }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $appName }}
  labels:
    {{- include "web-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "web-service.labels" . | nindent 6}}
  endpoints:
    - port: http
      {{- with .Values.prometheusServiceMonitor.basicAuth }}
      basicAuth:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
