# Default values for web-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

app:
  name: ""  # e.g., identity-uw, defaults to .Chart.Name

replicaCount: 1

flux:
  syncInterval: 5m0s

image:
  # The deploymentTag must be overridden in the corresponding
  # HelmRelease for flux; the value itself should also correspond
  # to an ImagePolicy object that can monitor the given
  # image repository for updated deployment tags.
  # An example in the release spec might look like this:
  #
  # kind: HelmRelease
  # spec:
  #   values:
  #     image:
  #       deploymentTag: ghcr.io/uwit-iam/example-flask-app:latest  # {"$imagepolicy": "default:example-app-policy"}
  deploymentTag: ghcr.io/uwit-iam/example-flask-app:latest
  pullPolicy: IfNotPresent

ports:
  # The port exposed on the container to handle http requests.
  containerHttpPort: 8000

probes:
  path: /status
  liveness:
    query_string: ~  # Set if needed for your application
    path: ~  # Will default to the root 'path'
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 3
  readiness:
    query_string: '?ready'  # Override if needed or nullify with ~
    path: ~  # Will default to the root 'path'
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 30
    successThreshold: 1
    timeoutSeconds: 3

podAnnotations: {}

prometheusServiceMonitor:
  enabled: false
  # To enable auth (recommended!), dependent apps would need to include
  # a map to the secret username and password, such as:
  # basicAuth:
  #   username:
  #     name: <secret_name>   # e.g., 'prom-servicemanager-secrets'
  #     key: <config_json_key>  # e.g., 'username'
  #   password:
  #     name: <secret_name>
  #     key: <config_json_key>  # e.g., 'password'
  #
  # in this case, the `prom-servicemanager-secrets` secret would need to be
  # json in the form of: "{username: 'promUserName', password: 'promP@55w0rd!'}"
  basicAuth: {}

environmentVariables: {}

environmentSecrets: {}
# If you have secrets stored in key-value pairs
# that you would like to map to environment variables,
# you can define those here in the following format.
# (and remove `{}` above):
#
#  dest: ENV_VAR_NAME
#  secretName: name-of-kubernetes-secret
#  key: someKeyInsideTheSecret


service:
  type: ClusterIP
  port: 80

ingress:
  # If disabled (default), you must provide your own
  # ingress configuration. This is meant to allow apps with
  # non-comformant ingresses to migrate to the helm chart in stages.
  enabled: false
  annotations: {}
  # Toggle this to false to disable automated letsencrypt cert rotation
  manageCertificates: true
  hosts: []
    #- host: chart-example.local
    #  paths:
    #    - path: /
    #    - pathType: ImplementationSpecific (default is "Prefix")
  tls:
    enabled: false
    entries: []
      #- secretName: chart-example-tls
      #  hosts:
      #    - chart-example.local
  saml:
    # If you enable saml integration, it is assumed that you
    # already have an nginx-saml-ingress integration set up
    # in your cluster.
    enabled: false
    # Fill in the id of the groups.uw.edu group that you
    # want to use to authenticate to your service.
    # ALL groups that you intend to use with this template
    # must be added as requested attributes. If you leave
    # this blank, _ANY_ logged in user will be able
    # to access your application. If that
    gws_group_id: ~
    proxy_host: http://nginx-saml-proxy

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# If ingress.saml.enabled is set to `true`,
# then an nginx volume and volumeMount entry
# will be added; you do not need to define them.
volumes: {}

volumeMounts: {}
