name: Publish new chart 
on:
  push:
    branches:
      - 'main'
    paths:
      - 'basic-web-service/Chart.yaml'
jobs:
  PublishChart:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Chart.yaml has changed, updating gh-pages branch'
      - name: Checkout 🛎
        uses: actions/checkout@v3
        with:
          # check out all branches
          fetch-depth: 0
      - name: Publish to Github Pages
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR_ID}+${GITHUB_ACTOR}@users.noreply.github.com" 
          git checkout gh-pages
          git rebase origin/main
          git push origin gh-pages
